---
version: 2.1

orbs:
  github: circleci/github-cli@2
  docker: circleci/docker@2

executors:
  arm64:
    environment:
      ARCH: arm64
    docker:
      - image: cimg/go:1.20
    resource_class: arm.large
  amd64:
    environment:
      ARCH: amd64
    docker:
      - image: cimg/go:1.20
    resource_class: large


jobs:
  build:
    parameters:
      executor:
        type: executor
        default: amd64
      push:
        type: boolean
        default: false
    executor: << parameters.executor >>
    steps:
      - setup_remote_docker
      - checkout
      - docker/check:
          registry: ghcr.io
          docker-username: CIRCLE_PROJECT_USERNAME
          docker-password: GITHUB_TOKEN
      - run:
          name: Docker build
          command: scripts/build
      - run:
          name: Tests
          command: scripts/test
      - store_test_results:
          path: build/test-results
      - run:
          name: Collect output
          command: scripts/package
      - when:
          condition:
            equal:
              - master
              - << pipeline.git.branch >>
          steps:
            - docker/push:
                registry: ghcr.io
                image: $CIRCLE_PROJECT_USERNAME/${CIRCLE_PROJECT_REPONAME}
                tag: $CIRCLE_BRANCH-$ARCH
      - when:
          condition: << parameters.push >>
          steps:
            - docker/push:
                registry: ghcr.io
                image: $CIRCLE_PROJECT_USERNAME/${CIRCLE_PROJECT_REPONAME}
                tag: $DOCKER_TAG
            - github/setup:
                version: "2.43.1"
            - run:
                name: Upload artifacts - $ARCH
                command: >-
                  gh release upload \
                    "$VERSION" \
                    ./dist/* \
                    --repo "$(git config --get remote.origin.url)"

  assemble-manifest:
    executor:
      name: docker/docker
    steps:
      - docker/check:
          registry: ghcr.io
          docker-username: CIRCLE_PROJECT_USERNAME
          docker-password: GITHUB_TOKEN
      - run:
          name: Create multiarch manifest
          command: >-
            docker manifest create
            ghcr.io/$CIRCLE_PROJECT_USERNAME/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_TAG}
            ghcr.io/$CIRCLE_PROJECT_USERNAME/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_TAG}-amd64
            ghcr.io/$CIRCLE_PROJECT_USERNAME/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_TAG}-arm64
      - run:
          name: Push multiarch manifest
          command: >-
            docker manifest push
            ghcr.io/$CIRCLE_PROJECT_USERNAME/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_TAG}

  draft-release:
    docker:
      - image: cimg/base:current
    resource_class: small
    steps:
      - github/setup:
          version: "2.43.1"
      - checkout
      - run:
          name: Create draft release
          command: >-
            gh release create "${CIRCLE_TAG}"
            --draft
            --prerelease
            --generate-notes
            --verify-tag


workflows:
  continuous:
    jobs:
      - build: &rc-build
          name: Release candidate build (AMD64)
          executor: amd64
          push: false
          context: github
          filters:
            tags:
              ignore: /.*/
      - build:
          <<: *rc-build
          name: Release candidate build (ARM64)
          executor: arm64

  tags:
    jobs:
      - draft-release:
          name: Create github release
          context: github
          filters: &filter-tags
            branches:
              ignore: /.*/
            tags:
              only: /.*/
      - build:
          <<: *rc-build
          name: Tagged AMD64 release
          push: true
          filters: *filter-tags
          requires:
            - "Create github release"
      - build:
          <<: *rc-build
          name: Tagged ARM64 release
          executor: arm64
          push: true
          filters: *filter-tags
          requires:
            - "Create github release"
      - assemble-manifest:
          context: github
          filters: *filter-tags
          requires:
            - "Tagged AMD64 release"
            - "Tagged ARM64 release"
