#!/bin/bash

set -eux pipefail

source "$(dirname $0)/version"

CI_ARGS=""
if [ "${CI:-}" = "true" ]; then
    CI_ARGS="--pull --build-arg BUILDKIT_INLINE_CACHE=1"
fi

export DOCKER_BUILDKIT=1
export BUILDKIT_PROGRESS=plain

# Build k3os docker container
echo "Building ${IMAGE_FQN}:${TAG}"
docker build \
    ${CI_ARGS} \
    --tag "${IMAGE_FQN}:${TAG}" \
    --tag "${IMAGE_FQN}:${BRANCH}-${ARCH}" \
    --build-arg "K3S_VERSION=${K3S_VERSION}" \
    --build-arg "KERNEL_VERSION=${KERNEL_VERSION}" \
    --build-arg "VERSION=${VERSION}" \
    --build-arg "BASE_VERSION=${BASE_VERSION}" \
    --build-arg "K3OS_BIN_VERSION=${K3OS_BIN_VERSION}" \
    --cache-from "${IMAGE_FQN}:${BRANCH}-${ARCH}" \
    --cache-from "${IMAGE_FQN}:${TAG}" \
    --target=image \
    --file "$(dirname $0)/../Dockerfile" \
    "$(dirname $0)/.."
