#!/bin/bash

set -eu

source "$(dirname $0)/version"

CI_ARGS=""
if [ "${CI:-}" = "true" ]; then
    CI_ARGS="--progress=plain --pull --build-arg BUILDKIT_INLINE_CACHE=1"
fi

export DOCKER_BUILDKIT=1

# Build k3os docker container
echo "Building ${IMAGE_FQN}:${TAG}"
docker build \
    ${CI_ARGS} \
    --tag "${IMAGE_FQN}:${TAG}" \
    --tag "${IMAGE_FQN}:${BRANCH}-${ARCH}" \
    --build-arg "K3S_VERSION=${K3S_VERSION}" \
    --build-arg "KERNEL_VERSION=${KERNEL_VERSION}" \
    --build-arg "KERNEL_URL=${KERNEL_URL}" \
    --build-arg "VERSION=${VERSION}" \
    --cache-from "${IMAGE_FQN}:${BRANCH}-${ARCH}" \
    --cache-from "${IMAGE_FQN}:${TAG}" \
    --target=image \
    --file "$(dirname $0)/../Dockerfile" \
    "$(dirname $0)/.."

# Build ISO container
echo "Building ${IMAGE_FQN}-iso:${TAG}"
docker build \
    ${CI_ARGS} \
    --tag "${IMAGE_FQN}-iso:${TAG}" \
    --tag "${IMAGE_FQN}-iso:${BRANCH}-${ARCH}" \
    --build-arg "K3S_VERSION=${K3S_VERSION}" \
    --build-arg "KERNEL_VERSION=${KERNEL_VERSION}" \
    --build-arg "KERNEL_URL=${KERNEL_URL}" \
    --build-arg "VERSION=${VERSION}" \
    --cache-from "${IMAGE_FQN}:${BRANCH}-${ARCH}" \
    --cache-from "${IMAGE_FQN}:${TAG}" \
    --target=iso \
    --file "$(dirname $0)/../Dockerfile" \
    "$(dirname $0)/.."
