#!/bin/bash

set -eu

source "$(dirname $0)/version"

export DOCKER_BUILDKIT=1

# Build k3os docker container
echo "Building ${IMAGE_FQN}:${TAG}"
docker build --progress=plain \
    --tag "${IMAGE_FQN}:${TAG}" \
    --tag "${IMAGE_FQN}:${BRANCH}-${ARCH}" \
    --build-arg "VERSION=${VERSION}" \
    --build-arg BUILDKIT_INLINE_CACHE=1 \
    --cache-from "${IMAGE_FQN}:${BRANCH}-${ARCH}" \
    --cache-from "${IMAGE_FQN}:${TAG}" \
    --target=image \
    --file "$(dirname $0)/../Dockerfile" \
    "$(dirname $0)/.."

# Build ISO container
echo "Building ${IMAGE_FQN}-iso:${TAG}"
docker build --progress=plain \
    --tag "${IMAGE_FQN}-iso:${TAG}" \
    --tag "${IMAGE_FQN}-iso:${BRANCH}-${ARCH}" \
    --build-arg "VERSION=${VERSION}" \
    --cache-from "${IMAGE_FQN}:${BRANCH}-${ARCH}" \
    --cache-from "${IMAGE_FQN}:${TAG}" \
    --target=iso \
    --file "$(dirname $0)/../Dockerfile" \
    "$(dirname $0)/.."
