#!/bin/bash

if [ -n "$(git status --porcelain --untracked-files=no)" ]; then
    DIRTY="-dirty"
fi

BRANCH="${CIRCLE_BRANCH:-$(git branch --show-current)}"
COMMIT=$(git rev-parse --short HEAD)
GIT_TAG=${CIRCLE_TAG:-$(git tag -l --contains HEAD | head -n 1)}
VERSION=${GIT_TAG}
if [[ -n "${DIRTY}" ]]; then
    VERSION=dev
elif [[ -z "${VERSION}" ]]; then
    VERSION="$(git describe --always --tags)${DIRTY}"
fi

if [ -z "${ARCH:-}" ]; then
    ARCH=$(go env GOHOSTARCH)
fi

if [ -z "${OS:-}" ]; then
    OS=$(go env GOHOSTOS)
fi

REGISTRY="docker.io"
if [[ "$(git config --get remote.origin.url)" =~ @github\.com: ]]; then
    REGISTRY="ghcr.io"
fi

ARCH=${ARCH:-"amd64"}
OS=${OS:-linux}
TAG=${TAG:-"${VERSION}-${ARCH}"}
REPO=${CIRCLE_PROJECT_USERNAME:-petercb}
IMAGE_NAME=${CIRCLE_PROJECT_REPONAME:-k3os}
IMAGE_FQN="${REGISTRY}/${REPO}/${IMAGE_NAME}"

echo "Version = ${VERSION}"
echo "Branch  = ${BRANCH}"
echo "Commit  = ${COMMIT}"
echo "OS      = ${OS}"
echo "Arch    = ${ARCH}"
echo "Image   = ${IMAGE_FQN}"

if [ "${CIRCLECI:-}" = "true" ]; then
    echo "export VERSION=${VERSION}" >> "${BASH_ENV:-/dev/null}"
fi
